# Generated by Django 5.0 on 2024-01-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cucumber_app', '0002_comment_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='static/images/default.jpg', null=True, upload_to='static/images/'),
        ),
    ]
