# Generated by Django 5.0 on 2024-01-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cucumber_app', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='static/images/default_image.jpg', null=True, upload_to='static/images/'),
        ),
    ]
