# Generated by Django 5.0 on 2024-01-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cucumber_app', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(default='no bio', max_length=50, null=True),
        ),
    ]
