# Generated by Django 5.0 on 2024-01-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cucumber_app', '0005_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='cucumber_app/static/images/default_image.jpg', null=True, upload_to='cucumber_app/static/images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='cucumber_app/static/images/default.jpg', null=True, upload_to='cucumber_app/static/images/'),
        ),
    ]
