# Generated by Django 5.0 on 2024-01-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cucumber_app', '0006_alter_post_image_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='cucumber_app/static/images/default_image.jpg', null=True, upload_to='media/static/images/image.png'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='cucumber_app/static/images/default.jpg', null=True, upload_to='media/static/images/image.png'),
        ),
    ]
