# Generated by Django 5.0 on 2024-01-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cucumber_app', '0011_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/static/images/image.png'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
